# apps/api/core/dependencies.py

"""
Authentication and authorization dependencies for FastAPI.

Provides:
- Session-based authentication
- Workspace context resolution
- Role-based access control
- Serverless-safe workspace schema access
"""

import logging
from typing import Annotated, Any
from uuid import UUID

import jwt
from fastapi import Depends, Request
from fastapi.security import HTTPBearer
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from core.auth.sessions import session_manager
from core.database import get_async_db_session
from core.exceptions.auth import AuthenticationError, AuthorizationError
from core.settings import settings
from models.agent import AgentScheduleRun
from models.user import User
from models.workspace import Workspace, WorkspaceMembership
from services.workspaces.get_default_workspace import require_default_workspace_membership_for_user
from services.workspaces.utils import EDITOR_ROLES, MANAGER_ROLES, READ_ROLES

logger = logging.getLogger(__name__)
_INTERNAL_TOKEN_WORKSPACE_ATTR = "_internal_token_workspace_id"
AsyncDbSessionDep = Annotated[AsyncSession, Depends(get_async_db_session)]


class SessionAuth(HTTPBearer):
    async def __call__(
        self,
        request: Request,
        db: AsyncDbSessionDep,
    ) -> User | None:
        # Check cookie first (regular session)
        session_token = request.cookies.get("session")

        # Fall back to Bearer token in Authorization header
        if not session_token:
            credentials = await super().__call__(request)
            if credentials:
                session_token = credentials.credentials

        if not session_token:
            return None

        # Try to validate as regular session first
        user = await session_manager.validate_session(db, session_token)
        if user:
            return user

        # If not a regular session, try to decode as JWT session token
        # (used for scheduled task execution)
        user = await self._validate_jwt_session_token(db, session_token)
        if user:
            return user

        return None

    async def _validate_jwt_session_token(self, db: AsyncSession, token: str) -> User | None:
        """
        Validate JWT session token (used for scheduled task executions).

        These tokens are generated by the service token validation endpoint
        and allow scheduled tasks to make authenticated API calls.
        """
        try:
            payload = jwt.decode(
                token, settings.SECRET_KEY.get_secret_value(), algorithms=["HS256"]
            )

            # Verify token type
            if payload.get("type") != "user_session_token":
                return None
            if not payload.get("jti") or payload.get("internal") is not True:
                return None

            # Extract user ID
            user_id_str = payload.get("user_id")
            if not user_id_str:
                return None

            # Fetch user from database
            user_id = UUID(user_id_str)
            workspace_id_str = payload.get("workspace_id")
            if not workspace_id_str:
                return None
            internal_workspace_id = UUID(workspace_id_str)

            schedule_run_id_str = payload.get("schedule_run_id")
            if schedule_run_id_str:
                schedule_run_id = UUID(schedule_run_id_str)
                schedule_run_result = await db.execute(
                    select(AgentScheduleRun).where(AgentScheduleRun.id == schedule_run_id)
                )
                schedule_run = schedule_run_result.scalar_one_or_none()
                if (
                    schedule_run is None
                    or schedule_run.deleted
                    or schedule_run.workspace_id != internal_workspace_id
                    or schedule_run.user_id != user_id
                ):
                    return None

            stmt = select(User).where(User.id == user_id, User.is_active.is_(True))
            result = await db.execute(stmt)
            user = result.scalar_one_or_none()

            if user:
                setattr(user, _INTERNAL_TOKEN_WORKSPACE_ATTR, internal_workspace_id)
                logger.debug("Validated JWT session token for user %s", user_id)
                return user

            return None

        except jwt.ExpiredSignatureError:
            logger.debug("JWT session token expired")
            return None
        except jwt.InvalidTokenError:
            logger.debug("Invalid JWT session token")
            return None
        except ValueError:
            # UUID parsing or other value errors — treat as an invalid token.
            logger.debug("Invalid value in JWT session token payload")
            return None
        except Exception:
            logger.error("Unexpected error validating JWT session token", exc_info=True)
            raise


# Auth dependencies
optional_auth = SessionAuth(auto_error=False)
OptionalUserDep = Annotated[User | None, Depends(optional_auth)]


async def get_current_user(user: OptionalUserDep) -> User:
    if not user:
        raise AuthenticationError("Not authenticated")
    return user


CurrentUserDep = Annotated[User, Depends(get_current_user)]


def is_super_admin_email(email: str | None) -> bool:
    """Return whether an email is listed as a super admin."""
    return (email or "").lower() in settings.super_admin_emails_list


def _enforce_internal_token_workspace(user: User, workspace: Workspace) -> None:
    internal_workspace_id = getattr(user, _INTERNAL_TOKEN_WORKSPACE_ATTR, None)
    if internal_workspace_id is not None and workspace.id != internal_workspace_id:
        raise AuthorizationError("Internal bearer token is not valid for this workspace")


async def get_current_workspace(
    request: Request,
    user: CurrentUserDep,
    db: AsyncDbSessionDep,
) -> tuple[Workspace, WorkspaceMembership]:
    """Resolve the current workspace from X-Workspace header or a safe fallback.

    Every user always has at least one workspace (personal, auto-created on signup).
    This dependency never returns None — it raises if an explicit workspace header
    is not available to the user or if no fallback workspace can be resolved.
    """
    workspace_slug: str | None = request.headers.get("X-Workspace")

    if workspace_slug:
        # Resolve from explicit header
        result = await db.execute(
            select(WorkspaceMembership)
            .options(selectinload(WorkspaceMembership.workspace))
            .where(
                WorkspaceMembership.user_id == user.id,
                WorkspaceMembership.workspace.has(slug=workspace_slug),
                WorkspaceMembership.deleted == False,  # noqa: E712
            ),
        )
        membership = result.scalar_one_or_none()

        if membership:
            _enforce_internal_token_workspace(user, membership.workspace)
            return membership.workspace, membership

        logger.warning(
            "Rejected invalid workspace header for user %s and workspace slug %s",
            user.id,
            workspace_slug,
        )
        raise AuthorizationError("Workspace not found or access denied")

    fallback_membership = await require_default_workspace_membership_for_user(db, user)
    _enforce_internal_token_workspace(user, fallback_membership.workspace)
    return fallback_membership.workspace, fallback_membership


CurrentWorkspaceDep = Annotated[
    tuple[Workspace, WorkspaceMembership], Depends(get_current_workspace)
]


async def get_current_user_context(
    user: CurrentUserDep,
    workspace_membership: CurrentWorkspaceDep,
) -> dict[str, Any]:
    """Get user context with workspace information and config flags."""
    workspace, membership = workspace_membership

    return {
        "user": user,
        "workspace": workspace,
        "membership": membership,
    }


async def require_super_admin(user: CurrentUserDep) -> User:
    """Dependency to check if user is a super admin.

    Returns the authenticated `User` when authorized; raises `AuthorizationError` otherwise.
    """
    if not is_super_admin_email(user.email):
        raise AuthorizationError(
            "Requires super admin role",
            details={
                "user_id": str(getattr(user, "id", None)),
                "email": user.email,
            },
        )
    return user


def require_role(allowed_roles: list[str]):
    """Dependency to check user role in the current workspace."""

    async def role_checker(
        workspace_membership: CurrentWorkspaceDep,
    ):
        workspace, membership = workspace_membership
        if membership.role not in allowed_roles:
            raise AuthorizationError(
                "Requires higher level role",
                details={
                    "allowed_roles": allowed_roles,
                    "membership_id": str(membership.id),
                    "membership_role": membership.role,
                    "workspace_id": str(membership.workspace_id),
                    "user_id": str(membership.user_id),
                },
            )
        return workspace, membership

    return role_checker


# Admins have equivalent permissions to owners in app semantics
require_owner = require_role(sorted(MANAGER_ROLES))
require_editor = require_role(sorted(EDITOR_ROLES))
require_read = require_role(sorted(READ_ROLES))
