# apps/api/services/integrations/domain.py

"""Closed integration status vocabulary and transition law."""

CONNECTION_STATUS_AUTH_PENDING = "auth_pending"
CONNECTION_STATUS_DISCOVERY_PENDING = "discovery_pending"
CONNECTION_STATUS_NEEDS_RESOURCE_SELECTION = "needs_resource_selection"
CONNECTION_STATUS_ACTIVE = "active"
CONNECTION_STATUS_DEGRADED = "degraded"
CONNECTION_STATUS_ERROR = "error"
CONNECTION_STATUS_REVOKED = "revoked"
CONNECTION_STATUS_NEEDS_REAUTH = "needs_reauth"

CONNECTION_STATUSES = frozenset(
    {
        CONNECTION_STATUS_AUTH_PENDING,
        CONNECTION_STATUS_DISCOVERY_PENDING,
        CONNECTION_STATUS_NEEDS_RESOURCE_SELECTION,
        CONNECTION_STATUS_ACTIVE,
        CONNECTION_STATUS_DEGRADED,
        CONNECTION_STATUS_ERROR,
        CONNECTION_STATUS_REVOKED,
        CONNECTION_STATUS_NEEDS_REAUTH,
    }
)
TERMINAL_CONNECTION_STATUSES = frozenset({CONNECTION_STATUS_REVOKED})

CONNECTION_STATUS_TRANSITIONS: dict[str, frozenset[str]] = {
    CONNECTION_STATUS_AUTH_PENDING: frozenset(
        {
            CONNECTION_STATUS_DISCOVERY_PENDING,
            CONNECTION_STATUS_ACTIVE,
            CONNECTION_STATUS_ERROR,
            CONNECTION_STATUS_REVOKED,
        }
    ),
    CONNECTION_STATUS_DISCOVERY_PENDING: frozenset(
        {
            CONNECTION_STATUS_NEEDS_RESOURCE_SELECTION,
            CONNECTION_STATUS_ACTIVE,
            CONNECTION_STATUS_DEGRADED,
            CONNECTION_STATUS_ERROR,
            CONNECTION_STATUS_NEEDS_REAUTH,
            CONNECTION_STATUS_REVOKED,
        }
    ),
    CONNECTION_STATUS_NEEDS_RESOURCE_SELECTION: frozenset(
        {
            CONNECTION_STATUS_ACTIVE,
            CONNECTION_STATUS_DISCOVERY_PENDING,
            CONNECTION_STATUS_NEEDS_REAUTH,
            CONNECTION_STATUS_ERROR,
            CONNECTION_STATUS_REVOKED,
        }
    ),
    CONNECTION_STATUS_ACTIVE: frozenset(
        {
            CONNECTION_STATUS_DEGRADED,
            CONNECTION_STATUS_NEEDS_REAUTH,
            CONNECTION_STATUS_DISCOVERY_PENDING,
            CONNECTION_STATUS_NEEDS_RESOURCE_SELECTION,
            CONNECTION_STATUS_ERROR,
            CONNECTION_STATUS_REVOKED,
        }
    ),
    CONNECTION_STATUS_DEGRADED: frozenset(
        {
            CONNECTION_STATUS_ACTIVE,
            CONNECTION_STATUS_DISCOVERY_PENDING,
            CONNECTION_STATUS_NEEDS_REAUTH,
            CONNECTION_STATUS_ERROR,
            CONNECTION_STATUS_REVOKED,
        }
    ),
    CONNECTION_STATUS_ERROR: frozenset(
        {
            CONNECTION_STATUS_DISCOVERY_PENDING,
            CONNECTION_STATUS_ACTIVE,
            CONNECTION_STATUS_NEEDS_REAUTH,
            CONNECTION_STATUS_REVOKED,
        }
    ),
    CONNECTION_STATUS_NEEDS_REAUTH: frozenset(
        {
            CONNECTION_STATUS_DISCOVERY_PENDING,
            CONNECTION_STATUS_ACTIVE,
            CONNECTION_STATUS_REVOKED,
        }
    ),
    CONNECTION_STATUS_REVOKED: frozenset(),
}
