# apps/api/integrations/google_ads/tools/__init__.py

"""Google Ads runtime-tool contributions."""

from .add_ad_group_negative_keywords import (
    DEFINITION as ADD_AD_GROUP_NEGATIVE_KEYWORDS_DEFINITION,
)
from .add_campaign_negative_keywords import (
    DEFINITION as ADD_CAMPAIGN_NEGATIVE_KEYWORDS_DEFINITION,
)
from .add_negative_keywords import DEFINITION as ADD_NEGATIVE_KEYWORDS_DEFINITION
from .apply_recommendations import DEFINITION as APPLY_RECOMMENDATIONS_DEFINITION
from .create_negative_keyword_list import DEFINITION as CREATE_NEGATIVE_KEYWORD_LIST_DEFINITION
from .dismiss_recommendations import DEFINITION as DISMISS_RECOMMENDATIONS_DEFINITION
from .link_negative_keyword_list import DEFINITION as LINK_NEGATIVE_KEYWORD_LIST_DEFINITION
from .remove_ad_group_negative_keywords import (
    DEFINITION as REMOVE_AD_GROUP_NEGATIVE_KEYWORDS_DEFINITION,
)
from .remove_campaign_negative_keywords import (
    DEFINITION as REMOVE_CAMPAIGN_NEGATIVE_KEYWORDS_DEFINITION,
)
from .remove_negative_keywords import DEFINITION as REMOVE_NEGATIVE_KEYWORDS_DEFINITION
from .run_report import DEFINITION as RUN_REPORT_DEFINITION
from .update_campaign_status import DEFINITION as UPDATE_CAMPAIGN_STATUS_DEFINITION
from .update_device_bid_modifiers import (
    DEFINITION as UPDATE_DEVICE_BID_MODIFIERS_DEFINITION,
)

TOOL_DEFINITIONS = (
    ADD_AD_GROUP_NEGATIVE_KEYWORDS_DEFINITION,
    ADD_CAMPAIGN_NEGATIVE_KEYWORDS_DEFINITION,
    ADD_NEGATIVE_KEYWORDS_DEFINITION,
    APPLY_RECOMMENDATIONS_DEFINITION,
    CREATE_NEGATIVE_KEYWORD_LIST_DEFINITION,
    DISMISS_RECOMMENDATIONS_DEFINITION,
    LINK_NEGATIVE_KEYWORD_LIST_DEFINITION,
    REMOVE_AD_GROUP_NEGATIVE_KEYWORDS_DEFINITION,
    REMOVE_NEGATIVE_KEYWORDS_DEFINITION,
    REMOVE_CAMPAIGN_NEGATIVE_KEYWORDS_DEFINITION,
    RUN_REPORT_DEFINITION,
    UPDATE_CAMPAIGN_STATUS_DEFINITION,
    UPDATE_DEVICE_BID_MODIFIERS_DEFINITION,
)

__all__ = ["TOOL_DEFINITIONS"]
