# apps/api/integrations/google_ads/tools/__init__.py

"""Google Ads runtime-tool contributions."""

from .add_ad_group_negative_keywords import (
    DEFINITION as ADD_AD_GROUP_NEGATIVE_KEYWORDS_DEFINITION,
)
from .add_campaign_negative_keywords import (
    DEFINITION as ADD_CAMPAIGN_NEGATIVE_KEYWORDS_DEFINITION,
)
from .add_negative_keywords import DEFINITION as ADD_NEGATIVE_KEYWORDS_DEFINITION
from .add_positive_keywords import DEFINITION as ADD_POSITIVE_KEYWORDS_DEFINITION
from .apply_recommendations import DEFINITION as APPLY_RECOMMENDATIONS_DEFINITION
from .assign_campaign_budgets import DEFINITION as ASSIGN_CAMPAIGN_BUDGETS_DEFINITION
from .create_campaign_budget import DEFINITION as CREATE_CAMPAIGN_BUDGET_DEFINITION
from .create_negative_keyword_list import DEFINITION as CREATE_NEGATIVE_KEYWORD_LIST_DEFINITION
from .dismiss_recommendations import DEFINITION as DISMISS_RECOMMENDATIONS_DEFINITION
from .get_report_field import DEFINITION as GET_REPORT_FIELD_DEFINITION
from .link_negative_keyword_list import DEFINITION as LINK_NEGATIVE_KEYWORD_LIST_DEFINITION
from .list_report_fields import DEFINITION as LIST_REPORT_FIELDS_DEFINITION
from .remove_ad_group_negative_keywords import (
    DEFINITION as REMOVE_AD_GROUP_NEGATIVE_KEYWORDS_DEFINITION,
)
from .remove_campaign_budgets import DEFINITION as REMOVE_CAMPAIGN_BUDGETS_DEFINITION
from .remove_campaign_negative_keywords import (
    DEFINITION as REMOVE_CAMPAIGN_NEGATIVE_KEYWORDS_DEFINITION,
)
from .remove_negative_keywords import DEFINITION as REMOVE_NEGATIVE_KEYWORDS_DEFINITION
from .run_report import DEFINITION as RUN_REPORT_DEFINITION
from .update_campaign_budget_amounts import (
    DEFINITION as UPDATE_CAMPAIGN_BUDGET_AMOUNTS_DEFINITION,
)
from .update_campaign_status import DEFINITION as UPDATE_CAMPAIGN_STATUS_DEFINITION
from .update_device_bid_modifiers import (
    DEFINITION as UPDATE_DEVICE_BID_MODIFIERS_DEFINITION,
)
from .update_positive_keyword_status import DEFINITION as UPDATE_POSITIVE_KEYWORD_STATUS_DEFINITION

TOOL_DEFINITIONS = (
    ADD_AD_GROUP_NEGATIVE_KEYWORDS_DEFINITION,
    ADD_CAMPAIGN_NEGATIVE_KEYWORDS_DEFINITION,
    ADD_NEGATIVE_KEYWORDS_DEFINITION,
    ADD_POSITIVE_KEYWORDS_DEFINITION,
    APPLY_RECOMMENDATIONS_DEFINITION,
    ASSIGN_CAMPAIGN_BUDGETS_DEFINITION,
    CREATE_CAMPAIGN_BUDGET_DEFINITION,
    CREATE_NEGATIVE_KEYWORD_LIST_DEFINITION,
    DISMISS_RECOMMENDATIONS_DEFINITION,
    GET_REPORT_FIELD_DEFINITION,
    LINK_NEGATIVE_KEYWORD_LIST_DEFINITION,
    LIST_REPORT_FIELDS_DEFINITION,
    REMOVE_AD_GROUP_NEGATIVE_KEYWORDS_DEFINITION,
    REMOVE_CAMPAIGN_BUDGETS_DEFINITION,
    REMOVE_NEGATIVE_KEYWORDS_DEFINITION,
    REMOVE_CAMPAIGN_NEGATIVE_KEYWORDS_DEFINITION,
    RUN_REPORT_DEFINITION,
    UPDATE_CAMPAIGN_STATUS_DEFINITION,
    UPDATE_CAMPAIGN_BUDGET_AMOUNTS_DEFINITION,
    UPDATE_DEVICE_BID_MODIFIERS_DEFINITION,
    UPDATE_POSITIVE_KEYWORD_STATUS_DEFINITION,
)

__all__ = ["TOOL_DEFINITIONS"]
