"""create core schema

Revision ID: core_0001
Revises:
Create Date: 2026-06-26 09:29:21.367639
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = 'core_0001'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = ('core',)
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pgcrypto"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "pg_trgm"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "citext"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "vector"')
    op.execute('CREATE EXTENSION IF NOT EXISTS "ltree"')
    op.create_table('agent_schedule_runs',
    sa.Column('schedule_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('claim_token', sa.UUID(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('claim_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service_token_jti', sa.UUID(), nullable=True),
    sa.Column('conversation_id', sa.UUID(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_code', sa.String(length=64), nullable=True),
    sa.Column('last_error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'claimed', 'accepted', 'running', 'awaiting_approval', 'completed', 'retryable_failed', 'terminal_failed', 'cancelled')", name='agent_schedule_runs_status_check'),
    sa.CheckConstraint('attempt_count >= 0', name='agent_schedule_runs_attempt_count_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'scheduled_for', name='uq_agent_schedule_runs_schedule_fire_time')
    )
    op.create_index(op.f('ix_agent_schedule_runs_agent_id'), 'agent_schedule_runs', ['agent_id'], unique=False)
    op.create_index('ix_agent_schedule_runs_claim_expiry', 'agent_schedule_runs', ['status', 'claim_expires_at'], unique=False, postgresql_where=sa.text("deleted = false AND status = 'claimed'"))
    op.create_index('ix_agent_schedule_runs_conversation', 'agent_schedule_runs', ['conversation_id'], unique=True, postgresql_where=sa.text('conversation_id IS NOT NULL'))
    op.create_index(op.f('ix_agent_schedule_runs_deleted_at'), 'agent_schedule_runs', ['deleted_at'], unique=False)
    op.create_index('ix_agent_schedule_runs_schedule_created', 'agent_schedule_runs', ['schedule_id', 'created_at'], unique=False, postgresql_where=sa.text('deleted = false'))
    op.create_index(op.f('ix_agent_schedule_runs_schedule_id'), 'agent_schedule_runs', ['schedule_id'], unique=False)
    op.create_index('ix_agent_schedule_runs_service_token_jti', 'agent_schedule_runs', ['service_token_jti'], unique=True, postgresql_where=sa.text('service_token_jti IS NOT NULL'))
    op.create_index(op.f('ix_agent_schedule_runs_user_id'), 'agent_schedule_runs', ['user_id'], unique=False)
    op.create_index(op.f('ix_agent_schedule_runs_workspace_id'), 'agent_schedule_runs', ['workspace_id'], unique=False)
    op.create_index('ix_agent_schedule_runs_workspace_status_due', 'agent_schedule_runs', ['workspace_id', 'status', 'scheduled_for'], unique=False, postgresql_where=sa.text('deleted = false'))
    op.create_table('conversations',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'active'"), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unread', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('source', sa.String(length=32), server_default=sa.text("'direct'"), nullable=False),
    sa.Column('schedule_id', sa.UUID(), nullable=True),
    sa.Column('schedule_run_id', sa.UUID(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active_agent_id', sa.UUID(), nullable=True),
    sa.Column('agent_slug', sa.String(length=128), nullable=True),
    sa.Column('agent_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("source IN ('direct', 'scheduled', 'agent_call')", name='conversations_source_check'),
    sa.CheckConstraint("status IN ('active', 'archived')", name='conversations_status_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_conversations_agent_slug'), 'conversations', ['agent_slug'], unique=False)
    op.create_index(op.f('ix_conversations_created_by'), 'conversations', ['created_by'], unique=False)
    op.create_index(op.f('ix_conversations_deleted_at'), 'conversations', ['deleted_at'], unique=False)
    op.create_index('ix_conversations_last_message', 'conversations', ['last_message_at'], unique=False)
    op.create_index('ix_conversations_schedule_id', 'conversations', ['schedule_id'], unique=False, postgresql_where=sa.text('schedule_id IS NOT NULL'))
    op.create_index('ix_conversations_schedule_run_id', 'conversations', ['schedule_run_id'], unique=True, postgresql_where=sa.text('schedule_run_id IS NOT NULL'))
    op.create_index('ix_conversations_source_agent', 'conversations', ['source', 'agent_slug'], unique=False)
    op.create_index('ix_conversations_unread', 'conversations', ['unread'], unique=False)
    op.create_index('ix_conversations_user_created', 'conversations', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversations_user_id'), 'conversations', ['user_id'], unique=False)
    op.create_index('ix_conversations_user_workspace_agent', 'conversations', ['user_id', 'workspace_id', 'agent_slug', 'created_at'], unique=False, postgresql_where=sa.text('deleted = false'))
    op.create_index('ix_conversations_workspace_created', 'conversations', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.create_table('rate_limit_attempts',
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('limit_type', sa.String(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address', 'endpoint', 'limit_type', 'window_seconds', 'window_start', name='uq_rate_limit_attempt_bucket')
    )
    op.create_index(op.f('ix_rate_limit_attempts_endpoint'), 'rate_limit_attempts', ['endpoint'], unique=False)
    op.create_index(op.f('ix_rate_limit_attempts_ip_address'), 'rate_limit_attempts', ['ip_address'], unique=False)
    op.create_index('ix_rate_limit_cleanup', 'rate_limit_attempts', ['created_at'], unique=False)
    op.create_table('security_events',
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('user_email', sa.String(length=320), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('request_id', sa.String(length=160), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_security_events_details', 'security_events', ['details'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_security_events_endpoint'), 'security_events', ['endpoint'], unique=False)
    op.create_index(op.f('ix_security_events_event_type'), 'security_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_security_events_ip_address'), 'security_events', ['ip_address'], unique=False)
    op.create_index('ix_security_events_ip_occurred', 'security_events', ['ip_address', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_security_events_request_id'), 'security_events', ['request_id'], unique=False)
    op.create_index('ix_security_events_type_occurred', 'security_events', ['event_type', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_security_events_user_email'), 'security_events', ['user_email'], unique=False)
    op.create_index('ix_security_events_user_occurred', 'security_events', ['user_email', 'occurred_at'], unique=False)
    op.create_table('users',
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('avatar_url', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('default_workspace_id', sa.UUID(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('totp_secret_encrypted', sa.Text(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('totp_enabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('backup_codes_encrypted', sa.Text(), nullable=True),
    sa.Column('backup_codes_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lockout_reason', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_users_default_workspace', 'users', ['default_workspace_id'], unique=False)
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_locked_until'), 'users', ['locked_until'], unique=False)
    op.create_table('conversation_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('parts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_name', sa.String(length=128), nullable=True),
    sa.Column('error', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('sequence', sa.BigInteger(), nullable=False),
    sa.Column('client_message_id', sa.String(length=128), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("role IN ('system', 'user', 'assistant', 'tool')", name='conversation_messages_role_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_conversation_messages_client_id', 'conversation_messages', ['conversation_id', 'client_message_id'], unique=True, postgresql_where=sa.text('client_message_id IS NOT NULL'))
    op.create_index(op.f('ix_conversation_messages_conversation_id'), 'conversation_messages', ['conversation_id'], unique=False)
    op.create_index('ix_conversation_messages_conversation_sequence', 'conversation_messages', ['conversation_id', 'sequence'], unique=False)
    op.create_index(op.f('ix_conversation_messages_deleted_at'), 'conversation_messages', ['deleted_at'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_password_reset_expires_used', 'password_reset_tokens', ['expires_at', 'used_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_deleted_at'), 'password_reset_tokens', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_expires_at'), 'password_reset_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index('ix_password_reset_user_expires', 'password_reset_tokens', ['user_id', 'expires_at'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('twofa_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_deleted_at'), 'sessions', ['deleted_at'], unique=False)
    op.create_index('ix_sessions_expires_accessed', 'sessions', ['expires_at', 'last_accessed'], unique=False)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index('ix_sessions_ip_accessed', 'sessions', ['ip_address', 'last_accessed'], unique=False)
    op.create_index(op.f('ix_sessions_last_accessed'), 'sessions', ['last_accessed'], unique=False)
    op.create_index('ix_sessions_token_2fa', 'sessions', ['token_hash', 'twofa_verified'], unique=False)
    op.create_index(op.f('ix_sessions_token_hash'), 'sessions', ['token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_twofa_verified'), 'sessions', ['twofa_verified'], unique=False)
    op.create_index('ix_sessions_user_accessed', 'sessions', ['user_id', 'last_accessed'], unique=False)
    op.create_index('ix_sessions_user_expires', 'sessions', ['user_id', 'expires_at'], unique=False)
    op.create_index('ix_sessions_user_ip', 'sessions', ['user_id', 'ip_address'], unique=False)
    op.create_table('user_auth',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_user_id', sa.String(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('refresh_token_encrypted', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw_profile', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_user_auth_provider_provider_user_id')
    )
    op.create_index(op.f('ix_user_auth_deleted_at'), 'user_auth', ['deleted_at'], unique=False)
    op.create_index('ix_user_auth_email_provider', 'user_auth', ['email', 'provider'], unique=False)
    op.create_index('ix_user_auth_token_expires', 'user_auth', ['token_expires_at'], unique=False)
    op.create_index('ix_user_auth_user_provider', 'user_auth', ['user_id', 'provider'], unique=False)
    op.create_table('workspaces',
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('icon_url', sa.String(), nullable=True),
    sa.Column('is_personal', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(), server_default=sa.text("'active'"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_deleted_at'), 'workspaces', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_index('ix_workspaces_status_created', 'workspaces', ['status', 'created_at'], unique=False)
    op.create_table('agents',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('tool_names', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('tool_policies', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('skill_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('allowed_agent_ids', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('model_provider', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('model_settings', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('azure_deployment', sa.String(length=100), nullable=True),
    sa.Column('max_steps', sa.Integer(), server_default=sa.text('20'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_created_by'), 'agents', ['created_by'], unique=False)
    op.create_index(op.f('ix_agents_deleted_at'), 'agents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    op.create_index('ix_agents_name_workspace', 'agents', ['name', 'workspace_id'], unique=False)
    op.create_index(op.f('ix_agents_slug'), 'agents', ['slug'], unique=False)
    op.create_index('ix_agents_slug_workspace', 'agents', ['slug', 'workspace_id'], unique=True)
    op.create_index('ix_agents_workspace_created', 'agents', ['workspace_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_agents_workspace_id'), 'agents', ['workspace_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=100), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), server_default=sa.text("'success'"), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('actor_type', sa.String(length=50), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('actor_display', sa.String(length=255), nullable=True),
    sa.Column('requested_by_user_id', sa.UUID(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('request_id', sa.String(length=160), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_action'), 'audit_events', ['action'], unique=False)
    op.create_index('ix_audit_events_occurred_at', 'audit_events', ['occurred_at'], unique=False)
    op.create_index('ix_audit_events_actor_occurred', 'audit_events', ['actor_user_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index('ix_audit_events_details', 'audit_events', ['details'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_audit_events_request_id'), 'audit_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_events_requested_by_user_id'), 'audit_events', ['requested_by_user_id'], unique=False)
    op.create_index('ix_audit_events_resource_occurred', 'audit_events', ['resource_type', 'resource_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_resource_type'), 'audit_events', ['resource_type'], unique=False)
    op.create_index('ix_audit_events_status_occurred', 'audit_events', ['status', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_workspace_id'), 'audit_events', ['workspace_id'], unique=False)
    op.create_index('ix_audit_events_workspace_occurred', 'audit_events', ['workspace_id', 'occurred_at'], unique=False)
    op.create_table('notifications',
    sa.Column('recipient_user_id', sa.UUID(), nullable=True),
    sa.Column('target_email', postgresql.CITEXT(), nullable=True),
    sa.Column('workspace_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('actioned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('action_taken', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_deleted_at'), 'notifications', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_notifications_read_at'), 'notifications', ['read_at'], unique=False)
    op.create_index(op.f('ix_notifications_recipient_user_id'), 'notifications', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_notifications_target_email'), 'notifications', ['target_email'], unique=False)
    op.create_index(op.f('ix_notifications_notification_type'), 'notifications', ['notification_type'], unique=False)
    op.create_index('ix_notifications_user_created', 'notifications', ['recipient_user_id', 'created_at'], unique=False)
    op.create_index('ix_notifications_user_read', 'notifications', ['recipient_user_id', 'read_at'], unique=False)
    op.create_index('ix_notifications_workspaces', 'notifications', ['workspace_id'], unique=False)
    op.create_table('skills',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('human_name', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('documentation_refs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'name', name='uq_skills_workspace_name')
    )
    op.create_index('idx_skills_active', 'skills', ['is_active'], unique=False, postgresql_where=sa.text('is_active = true'))
    op.create_index('idx_skills_workspace', 'skills', ['workspace_id'], unique=False)
    op.create_index(op.f('ix_skills_created_by'), 'skills', ['created_by'], unique=False)
    op.create_index(op.f('ix_skills_deleted_at'), 'skills', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_skills_name'), 'skills', ['name'], unique=False)
    op.create_index('ix_skills_workspace_created', 'skills', ['workspace_id', 'created_at'], unique=False)
    op.create_table('workspace_invitations',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('role', sa.String(), server_default=sa.text("'member'"), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member', 'read_only')", name='workspace_invitations_role_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_workspace_invitations_created_at', 'workspace_invitations', ['created_at'], unique=False)
    op.create_index(op.f('ix_workspace_invitations_deleted_at'), 'workspace_invitations', ['deleted_at'], unique=False)
    op.create_index('ix_workspace_invitations_email_workspace', 'workspace_invitations', ['email', 'workspace_id'], unique=False)
    op.create_index(op.f('ix_workspace_invitations_expires_at'), 'workspace_invitations', ['expires_at'], unique=False)
    op.create_index('ix_workspace_invitations_role', 'workspace_invitations', ['role'], unique=False)
    op.create_index(op.f('ix_workspace_invitations_token_hash'), 'workspace_invitations', ['token_hash'], unique=True)
    op.create_index('ix_workspace_invitations_workspace_email', 'workspace_invitations', ['workspace_id', 'email'], unique=False)
    op.create_index('uq_workspace_invitations_pending', 'workspace_invitations', ['workspace_id', 'email'], unique=True, postgresql_where=sa.text('accepted_at IS NULL AND deleted = false'))
    op.create_table('workspace_memberships',
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), server_default=sa.text("'member'"), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("role IN ('owner', 'admin', 'member', 'read_only')", name='workspace_memberships_role_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'user_id')
    )
    op.create_index('ix_workspace_memberships_created_at', 'workspace_memberships', ['created_at'], unique=False)
    op.create_index(op.f('ix_workspace_memberships_deleted_at'), 'workspace_memberships', ['deleted_at'], unique=False)
    op.create_index('ix_workspace_memberships_role', 'workspace_memberships', ['role'], unique=False)
    op.create_index('ix_workspace_memberships_user_workspace', 'workspace_memberships', ['user_id', 'workspace_id'], unique=False)
    op.create_table('agent_schedules',
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('workspace_id', sa.UUID(), nullable=False),
    sa.Column('schedule_type', sa.String(), nullable=False),
    sa.Column('cron_expression', sa.String(), nullable=True),
    sa.Column('interval_minutes', sa.Integer(), nullable=True),
    sa.Column('run_once_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('timezone', sa.String(length=64), server_default=sa.text("'UTC'"), nullable=False),
    sa.Column('default_prompt', sa.Text(), nullable=True),
    sa.Column('execution_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('active_context', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("schedule_type IN ('cron', 'interval', 'once')", name='agent_schedules_schedule_type_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_schedules_agent_id'), 'agent_schedules', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_schedules_deleted_at'), 'agent_schedules', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_agent_schedules_user_id'), 'agent_schedules', ['user_id'], unique=False)
    op.create_index('ix_agent_schedules_workspace_active', 'agent_schedules', ['workspace_id', 'is_active', 'created_at'], unique=False, postgresql_where=sa.text('deleted = false'))
    op.create_index(op.f('ix_agent_schedules_workspace_id'), 'agent_schedules', ['workspace_id'], unique=False)
    op.create_foreign_key('fk_agent_schedule_runs_agent_id_agents', 'agent_schedule_runs', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agent_schedule_runs_conversation_id_conversations', 'agent_schedule_runs', 'conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_agent_schedule_runs_deleted_by_users', 'agent_schedule_runs', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_agent_schedule_runs_schedule_id_agent_schedules', 'agent_schedule_runs', 'agent_schedules', ['schedule_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agent_schedule_runs_user_id_users', 'agent_schedule_runs', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_agent_schedule_runs_workspace_id_workspaces', 'agent_schedule_runs', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key('fk_conversations_active_agent_id_agents', 'conversations', 'agents', ['active_agent_id'], ['id'])
    op.create_foreign_key('fk_conversations_created_by_users', 'conversations', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_conversations_deleted_by_users', 'conversations', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_conversations_schedule_id_agent_schedules', 'conversations', 'agent_schedules', ['schedule_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_conversations_schedule_run_id_agent_schedule_runs', 'conversations', 'agent_schedule_runs', ['schedule_run_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_conversations_user_id_users', 'conversations', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_conversations_workspace_id_workspaces', 'conversations', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key('fk_users_default_workspace_id_workspaces', 'users', 'workspaces', ['default_workspace_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_users_deleted_by_users', 'users', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_conversation_messages_conversation_id_conversations', 'conversation_messages', 'conversations', ['conversation_id'], ['id'])
    op.create_foreign_key('fk_conversation_messages_deleted_by_users', 'conversation_messages', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_password_reset_tokens_deleted_by_users', 'password_reset_tokens', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_password_reset_tokens_user_id_users', 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_sessions_deleted_by_users', 'sessions', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_sessions_user_id_users', 'sessions', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_user_auth_deleted_by_users', 'user_auth', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_user_auth_user_id_users', 'user_auth', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_workspaces_deleted_by_users', 'workspaces', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_agents_created_by_users', 'agents', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_agents_deleted_by_users', 'agents', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_agents_workspace_id_workspaces', 'agents', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key('fk_audit_events_actor_user_id_users', 'audit_events', 'users', ['actor_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_audit_events_requested_by_user_id_users', 'audit_events', 'users', ['requested_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_audit_events_workspace_id_workspaces', 'audit_events', 'workspaces', ['workspace_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_notifications_deleted_by_users', 'notifications', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_notifications_recipient_user_id_users', 'notifications', 'users', ['recipient_user_id'], ['id'])
    op.create_foreign_key('fk_notifications_workspace_id_workspaces', 'notifications', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key('fk_skills_created_by_users', 'skills', 'users', ['created_by'], ['id'])
    op.create_foreign_key('fk_skills_deleted_by_users', 'skills', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_skills_workspace_id_workspaces', 'skills', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_workspace_invitations_deleted_by_users', 'workspace_invitations', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_workspace_invitations_invited_by_users', 'workspace_invitations', 'users', ['invited_by'], ['id'])
    op.create_foreign_key('fk_workspace_invitations_workspace_id_workspaces', 'workspace_invitations', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key('fk_workspace_memberships_deleted_by_users', 'workspace_memberships', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_workspace_memberships_user_id_users', 'workspace_memberships', 'users', ['user_id'], ['id'])
    op.create_foreign_key('fk_workspace_memberships_workspace_id_workspaces', 'workspace_memberships', 'workspaces', ['workspace_id'], ['id'])
    op.create_foreign_key('fk_agent_schedules_agent_id_agents', 'agent_schedules', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agent_schedules_deleted_by_users', 'agent_schedules', 'users', ['deleted_by'], ['id'])
    op.create_foreign_key('fk_agent_schedules_user_id_users', 'agent_schedules', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('fk_agent_schedules_workspace_id_workspaces', 'agent_schedules', 'workspaces', ['workspace_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert schema changes."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_agent_schedules_workspace_id_workspaces', 'agent_schedules', type_='foreignkey')
    op.drop_constraint('fk_agent_schedules_user_id_users', 'agent_schedules', type_='foreignkey')
    op.drop_constraint('fk_agent_schedules_deleted_by_users', 'agent_schedules', type_='foreignkey')
    op.drop_constraint('fk_agent_schedules_agent_id_agents', 'agent_schedules', type_='foreignkey')
    op.drop_constraint('fk_workspace_memberships_workspace_id_workspaces', 'workspace_memberships', type_='foreignkey')
    op.drop_constraint('fk_workspace_memberships_user_id_users', 'workspace_memberships', type_='foreignkey')
    op.drop_constraint('fk_workspace_memberships_deleted_by_users', 'workspace_memberships', type_='foreignkey')
    op.drop_constraint('fk_workspace_invitations_workspace_id_workspaces', 'workspace_invitations', type_='foreignkey')
    op.drop_constraint('fk_workspace_invitations_invited_by_users', 'workspace_invitations', type_='foreignkey')
    op.drop_constraint('fk_workspace_invitations_deleted_by_users', 'workspace_invitations', type_='foreignkey')
    op.drop_constraint('fk_skills_workspace_id_workspaces', 'skills', type_='foreignkey')
    op.drop_constraint('fk_skills_deleted_by_users', 'skills', type_='foreignkey')
    op.drop_constraint('fk_skills_created_by_users', 'skills', type_='foreignkey')
    op.drop_constraint('fk_notifications_workspace_id_workspaces', 'notifications', type_='foreignkey')
    op.drop_constraint('fk_notifications_recipient_user_id_users', 'notifications', type_='foreignkey')
    op.drop_constraint('fk_notifications_deleted_by_users', 'notifications', type_='foreignkey')
    op.drop_constraint('fk_audit_events_workspace_id_workspaces', 'audit_events', type_='foreignkey')
    op.drop_constraint('fk_audit_events_requested_by_user_id_users', 'audit_events', type_='foreignkey')
    op.drop_constraint('fk_audit_events_actor_user_id_users', 'audit_events', type_='foreignkey')
    op.drop_constraint('fk_agents_workspace_id_workspaces', 'agents', type_='foreignkey')
    op.drop_constraint('fk_agents_deleted_by_users', 'agents', type_='foreignkey')
    op.drop_constraint('fk_agents_created_by_users', 'agents', type_='foreignkey')
    op.drop_constraint('fk_workspaces_deleted_by_users', 'workspaces', type_='foreignkey')
    op.drop_constraint('fk_user_auth_user_id_users', 'user_auth', type_='foreignkey')
    op.drop_constraint('fk_user_auth_deleted_by_users', 'user_auth', type_='foreignkey')
    op.drop_constraint('fk_sessions_user_id_users', 'sessions', type_='foreignkey')
    op.drop_constraint('fk_sessions_deleted_by_users', 'sessions', type_='foreignkey')
    op.drop_constraint('fk_password_reset_tokens_user_id_users', 'password_reset_tokens', type_='foreignkey')
    op.drop_constraint('fk_password_reset_tokens_deleted_by_users', 'password_reset_tokens', type_='foreignkey')
    op.drop_constraint('fk_conversation_messages_deleted_by_users', 'conversation_messages', type_='foreignkey')
    op.drop_constraint('fk_conversation_messages_conversation_id_conversations', 'conversation_messages', type_='foreignkey')
    op.drop_constraint('fk_users_deleted_by_users', 'users', type_='foreignkey')
    op.drop_constraint('fk_users_default_workspace_id_workspaces', 'users', type_='foreignkey')
    op.drop_constraint('fk_conversations_workspace_id_workspaces', 'conversations', type_='foreignkey')
    op.drop_constraint('fk_conversations_user_id_users', 'conversations', type_='foreignkey')
    op.drop_constraint('fk_conversations_schedule_run_id_agent_schedule_runs', 'conversations', type_='foreignkey')
    op.drop_constraint('fk_conversations_schedule_id_agent_schedules', 'conversations', type_='foreignkey')
    op.drop_constraint('fk_conversations_deleted_by_users', 'conversations', type_='foreignkey')
    op.drop_constraint('fk_conversations_created_by_users', 'conversations', type_='foreignkey')
    op.drop_constraint('fk_conversations_active_agent_id_agents', 'conversations', type_='foreignkey')
    op.drop_constraint('fk_agent_schedule_runs_workspace_id_workspaces', 'agent_schedule_runs', type_='foreignkey')
    op.drop_constraint('fk_agent_schedule_runs_user_id_users', 'agent_schedule_runs', type_='foreignkey')
    op.drop_constraint('fk_agent_schedule_runs_schedule_id_agent_schedules', 'agent_schedule_runs', type_='foreignkey')
    op.drop_constraint('fk_agent_schedule_runs_deleted_by_users', 'agent_schedule_runs', type_='foreignkey')
    op.drop_constraint('fk_agent_schedule_runs_conversation_id_conversations', 'agent_schedule_runs', type_='foreignkey')
    op.drop_constraint('fk_agent_schedule_runs_agent_id_agents', 'agent_schedule_runs', type_='foreignkey')
    op.drop_index(op.f('ix_agent_schedules_workspace_id'), table_name='agent_schedules')
    op.drop_index('ix_agent_schedules_workspace_active', table_name='agent_schedules', postgresql_where=sa.text('deleted = false'))
    op.drop_index(op.f('ix_agent_schedules_user_id'), table_name='agent_schedules')
    op.drop_index(op.f('ix_agent_schedules_deleted_at'), table_name='agent_schedules')
    op.drop_index(op.f('ix_agent_schedules_agent_id'), table_name='agent_schedules')
    op.drop_table('agent_schedules')
    op.drop_index('ix_workspace_memberships_user_workspace', table_name='workspace_memberships')
    op.drop_index('ix_workspace_memberships_role', table_name='workspace_memberships')
    op.drop_index(op.f('ix_workspace_memberships_deleted_at'), table_name='workspace_memberships')
    op.drop_index('ix_workspace_memberships_created_at', table_name='workspace_memberships')
    op.drop_table('workspace_memberships')
    op.drop_index('uq_workspace_invitations_pending', table_name='workspace_invitations', postgresql_where=sa.text('accepted_at IS NULL AND deleted = false'))
    op.drop_index('ix_workspace_invitations_workspace_email', table_name='workspace_invitations')
    op.drop_index(op.f('ix_workspace_invitations_token_hash'), table_name='workspace_invitations')
    op.drop_index('ix_workspace_invitations_role', table_name='workspace_invitations')
    op.drop_index(op.f('ix_workspace_invitations_expires_at'), table_name='workspace_invitations')
    op.drop_index('ix_workspace_invitations_email_workspace', table_name='workspace_invitations')
    op.drop_index(op.f('ix_workspace_invitations_deleted_at'), table_name='workspace_invitations')
    op.drop_index('ix_workspace_invitations_created_at', table_name='workspace_invitations')
    op.drop_table('workspace_invitations')
    op.drop_index('ix_skills_workspace_created', table_name='skills')
    op.drop_index(op.f('ix_skills_name'), table_name='skills')
    op.drop_index(op.f('ix_skills_deleted_at'), table_name='skills')
    op.drop_index(op.f('ix_skills_created_by'), table_name='skills')
    op.drop_index('idx_skills_workspace', table_name='skills')
    op.drop_index('idx_skills_active', table_name='skills', postgresql_where=sa.text('is_active = true'))
    op.drop_table('skills')
    op.drop_index('ix_notifications_workspaces', table_name='notifications')
    op.drop_index('ix_notifications_user_read', table_name='notifications')
    op.drop_index('ix_notifications_user_created', table_name='notifications')
    op.drop_index(op.f('ix_notifications_notification_type'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_target_email'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_recipient_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_read_at'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_deleted_at'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_audit_events_workspace_occurred', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_workspace_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_status_occurred', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_resource_type'), table_name='audit_events')
    op.drop_index('ix_audit_events_resource_occurred', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_requested_by_user_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_request_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_details', table_name='audit_events', postgresql_using='gin')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_index('ix_audit_events_actor_occurred', table_name='audit_events')
    op.drop_index('ix_audit_events_occurred_at', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_action'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_agents_workspace_id'), table_name='agents')
    op.drop_index('ix_agents_workspace_created', table_name='agents')
    op.drop_index('ix_agents_slug_workspace', table_name='agents')
    op.drop_index(op.f('ix_agents_slug'), table_name='agents')
    op.drop_index('ix_agents_name_workspace', table_name='agents')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_deleted_at'), table_name='agents')
    op.drop_index(op.f('ix_agents_created_by'), table_name='agents')
    op.drop_table('agents')
    op.drop_index('ix_workspaces_status_created', table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_deleted_at'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index('ix_user_auth_user_provider', table_name='user_auth')
    op.drop_index('ix_user_auth_token_expires', table_name='user_auth')
    op.drop_index('ix_user_auth_email_provider', table_name='user_auth')
    op.drop_index(op.f('ix_user_auth_deleted_at'), table_name='user_auth')
    op.drop_table('user_auth')
    op.drop_index('ix_sessions_user_ip', table_name='sessions')
    op.drop_index('ix_sessions_user_expires', table_name='sessions')
    op.drop_index('ix_sessions_user_accessed', table_name='sessions')
    op.drop_index(op.f('ix_sessions_twofa_verified'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_token_hash'), table_name='sessions')
    op.drop_index('ix_sessions_token_2fa', table_name='sessions')
    op.drop_index(op.f('ix_sessions_last_accessed'), table_name='sessions')
    op.drop_index('ix_sessions_ip_accessed', table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index('ix_sessions_expires_accessed', table_name='sessions')
    op.drop_index(op.f('ix_sessions_deleted_at'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_password_reset_user_expires', table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_expires_at'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_password_reset_tokens_deleted_at'), table_name='password_reset_tokens')
    op.drop_index('ix_password_reset_expires_used', table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_conversation_messages_deleted_at'), table_name='conversation_messages')
    op.drop_index('ix_conversation_messages_conversation_sequence', table_name='conversation_messages')
    op.drop_index(op.f('ix_conversation_messages_conversation_id'), table_name='conversation_messages')
    op.drop_index('ix_conversation_messages_client_id', table_name='conversation_messages', postgresql_where=sa.text('client_message_id IS NOT NULL'))
    op.drop_table('conversation_messages')
    op.drop_index(op.f('ix_users_locked_until'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_index('ix_users_default_workspace', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_security_events_user_occurred', table_name='security_events')
    op.drop_index(op.f('ix_security_events_user_email'), table_name='security_events')
    op.drop_index('ix_security_events_type_occurred', table_name='security_events')
    op.drop_index(op.f('ix_security_events_request_id'), table_name='security_events')
    op.drop_index('ix_security_events_ip_occurred', table_name='security_events')
    op.drop_index(op.f('ix_security_events_ip_address'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_event_type'), table_name='security_events')
    op.drop_index(op.f('ix_security_events_endpoint'), table_name='security_events')
    op.drop_index('ix_security_events_details', table_name='security_events', postgresql_using='gin')
    op.drop_table('security_events')
    op.drop_index('ix_rate_limit_cleanup', table_name='rate_limit_attempts')
    op.drop_index(op.f('ix_rate_limit_attempts_ip_address'), table_name='rate_limit_attempts')
    op.drop_index(op.f('ix_rate_limit_attempts_endpoint'), table_name='rate_limit_attempts')
    op.drop_table('rate_limit_attempts')
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_index('ix_conversations_workspace_created', table_name='conversations')
    op.drop_index('ix_conversations_user_workspace_agent', table_name='conversations', postgresql_where=sa.text('deleted = false'))
    op.drop_index(op.f('ix_conversations_user_id'), table_name='conversations')
    op.drop_index('ix_conversations_user_created', table_name='conversations')
    op.drop_index('ix_conversations_unread', table_name='conversations')
    op.drop_index('ix_conversations_source_agent', table_name='conversations')
    op.drop_index('ix_conversations_schedule_run_id', table_name='conversations', postgresql_where=sa.text('schedule_run_id IS NOT NULL'))
    op.drop_index('ix_conversations_schedule_id', table_name='conversations', postgresql_where=sa.text('schedule_id IS NOT NULL'))
    op.drop_index('ix_conversations_last_message', table_name='conversations')
    op.drop_index(op.f('ix_conversations_deleted_at'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_created_by'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_agent_slug'), table_name='conversations')
    op.drop_table('conversations')
    op.drop_index('ix_agent_schedule_runs_workspace_status_due', table_name='agent_schedule_runs', postgresql_where=sa.text('deleted = false'))
    op.drop_index(op.f('ix_agent_schedule_runs_workspace_id'), table_name='agent_schedule_runs')
    op.drop_index(op.f('ix_agent_schedule_runs_user_id'), table_name='agent_schedule_runs')
    op.drop_index('ix_agent_schedule_runs_service_token_jti', table_name='agent_schedule_runs', postgresql_where=sa.text('service_token_jti IS NOT NULL'))
    op.drop_index(op.f('ix_agent_schedule_runs_schedule_id'), table_name='agent_schedule_runs')
    op.drop_index('ix_agent_schedule_runs_schedule_created', table_name='agent_schedule_runs', postgresql_where=sa.text('deleted = false'))
    op.drop_index(op.f('ix_agent_schedule_runs_deleted_at'), table_name='agent_schedule_runs')
    op.drop_index('ix_agent_schedule_runs_conversation', table_name='agent_schedule_runs', postgresql_where=sa.text('conversation_id IS NOT NULL'))
    op.drop_index('ix_agent_schedule_runs_claim_expiry', table_name='agent_schedule_runs', postgresql_where=sa.text("deleted = false AND status = 'claimed'"))
    op.drop_index(op.f('ix_agent_schedule_runs_agent_id'), table_name='agent_schedule_runs')
    op.drop_table('agent_schedule_runs')
    # ### end Alembic commands ###
